# Generated by Django 2.0.3 on 2018-03-14 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_auto_20180313_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('Speciality', models.CharField(max_length=250)),
                ('Hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
                ('is_booked', models.BooleanField()),
            ],
        ),
    ]
