# Generated by Django 2.0.3 on 2018-03-14 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0004_doctors_timing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=250)),
                ('contact_no', models.IntegerField()),
                ('Address', models.CharField(max_length=250)),
                ('Doctor_attending', models.CharField(max_length=250)),
                ('Appointment_no', models.CharField(max_length=250)),
                ('is_checked_out', models.BooleanField()),
                ('type1', models.BooleanField()),
                ('type2', models.BooleanField()),
                ('type3', models.BooleanField()),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Hospital')),
            ],
        ),
        migrations.DeleteModel(
            name='Timing',
        ),
    ]
