# Generated by Django 2.0.3 on 2018-03-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0006_auto_20180314_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='app_no',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
