# Generated by Django 2.0.3 on 2018-03-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0007_doctors_app_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='type1',
            field=models.CharField(default='N', max_length=10),
        ),
        migrations.AlterField(
            model_name='records',
            name='type2',
            field=models.CharField(default='N', max_length=10),
        ),
        migrations.AlterField(
            model_name='records',
            name='type3',
            field=models.CharField(default='N', max_length=10),
        ),
    ]
