# Generated by Django 2.0.3 on 2018-03-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0009_auto_20180315_0658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='app_no',
            new_name='assigned_app_no',
        ),
        migrations.RemoveField(
            model_name='records',
            name='Appointment_no',
        ),
        migrations.RemoveField(
            model_name='records',
            name='is_checked_out',
        ),
        migrations.AddField(
            model_name='doctors',
            name='current_app_no',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='records',
            name='speciality',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='records',
            name='Doctor_attending',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
