# Generated by Django 2.0.3 on 2018-03-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0010_auto_20180315_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='speciality',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
