# Generated by Django 2.0.3 on 2018-03-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0011_auto_20180315_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='Speciality',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
