# Generated by Django 2.0.3 on 2018-03-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0012_auto_20180315_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='Speciality',
            field=models.CharField(blank=True, default=0, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='speciality',
            field=models.CharField(blank=True, default=0, max_length=250, null=True),
        ),
    ]
