# Generated by Django 2.0.3 on 2018-03-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0014_auto_20180315_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='Address',
            field=models.CharField(blank=True, default=0, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='Doctor_attending',
            field=models.CharField(blank=True, default=0, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='contact_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
