# Generated by Django 2.0.3 on 2018-03-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0015_auto_20180315_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='type1',
            field=models.CharField(blank=True, default='N', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='type2',
            field=models.CharField(blank=True, default='N', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='type3',
            field=models.CharField(blank=True, default='N', max_length=10, null=True),
        ),
    ]
