# Generated by Django 2.0.3 on 2018-03-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0016_auto_20180315_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
            ],
        ),
    ]
