# Generated by Django 2.0.3 on 2018-03-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0018_auto_20180316_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='patient_name',
            field=models.CharField(max_length=250),
        ),
    ]
