# Generated by Django 2.0.3 on 2018-03-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0019_auto_20180316_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='patient_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
